export { GiftListsPage } from "./Gifts";
export { ModeratorListsPage } from "./Moderator-lists";
export { NotFoundPage } from "./Not-found";
export { PrivacyPolicy } from "./Privacy-policy";
export { TermsAndConditions } from "./Terms-and-conditions";
export { UserListsPage } from "./User-lists";
export { DashboardPage } from "./Dashboard";
export { UpdateSubAdminPermissionsPage } from "./UpdateSubAdminPermissions";
export { default as BannersPage } from "./Banners";
export { default as CreateBannerPage } from "./CreateBanner";
export { default as UpdateBannerPage } from "./UpdateBanner";